# Introdução{-}

Para persuadir os eleitores de que suas políticas são benéficas, o partido no poder precisa de recursos escassos, como tempo de televisão e dinheiro para propaganda. Uma maneira de obter esses recursos é vender favores de políticas para aqueles que podem pagar por eles, seja por contribuições de campanha, políticas editoriais favoráveis ou influência direta sobre outros. Devido a assimetria de informação entre as preferências dos eleitores e as ações do governo requer-se o uso de recursos econômicos para cobrir o custo da informação. Este resultado não é o resultado de irracionalidade ou desonestidade. @downs1957economic defende que fazer lobby em uma democracia é uma resposta altamente racional à falta de informação perfeita, assim como a submissão do governo às demandas dos lobistas.

O custo dessa atividade lobista está associado a atividades de *rent seeking*, como demonstrado por @buchanan1965calculus, @krueger1974political, @posner1975social e @olson1996distinguished. Outros trabalhos que analisam a relação entre eleições e atividade de *lobby*, observaram que os políticos eleitos beneficiavam mais os grupos com mais eleitores indecisos ou com eleitores mais informados. Além disso, o benefício destes grupos é maior se as contribuições de campanha são mais eficazes para influenciar os eleitores [baron1994electoral; @grossman1996electoral; @bennedsen2003vote]. Outros autores focam no Congresso para avaliar de que forma as doações de campanha influenciam as ações dos parlamentares [@langbein1986money ;@schuler1999dollars].

Especificamente para o Brasil, pesquisas como as de @samuels2001money, @peixoto2010eleiccoes, e @mancuso2015financiamento concluem que o dinheiro tem um papel importante na definição dos resultados eleitorais. @portugal2003financiamento analisam os impactos do financiamento público das campanhas eleitorais sobre a política adotada pelo partido majoritário no pleito eleitoral e  também sobre a representação resultante dos partidos no congresso. Os autores concluem que quando existem apenas doações privadas a política implementada favorece os grupos economicamente dominantes e a representação partidária no Legislativo é equilibrada. Porém, se as campanhas eleitorais forem financiadas exclusivamente pelo poder público, a política vencedora é socialmente ótima. O custo disso é que um único partido tende a ser dominante. No caso em que o financiamento das campanhas é misto, a política adotada é viesada em favor dos grupos mais fortes e a representação no Congresso torna-se assimétrica,  no longo prazo um partido torna-se dominante.

Nesse âmbito, em maio de 2015 iniciou-se na Câmara dos Deputados Federais uma série de votações que definiam novas regras sobre o financiamento de campanhas eleitorais. Todas foram apensadas à Proposta de Emenda Constitucional (PEC) 182/2007, que originalmente tratava de fidelidade partidária, mas no decorrer desse processo englobou diversos temas sobre o sistema político brasileiro e ficou conhecida como a Minirreforma Política.

Dentre as propostas, destaca-se a Emenda Aglutinativa (EMA) n.º 22. O texto permitia que Pessoas Físicas (PF) e Pessoas Jurídicas doassem recursos diretamente aos candidatos em suas campanhas eleitorais. A emenda foi rejeitada, eram necessários 3/5 dos votos dos Deputados, ou seja, 308 votos. No total, foram 251 votos Sim, 203 Não e 4 Abstenções.

Esta pesquisa busca responder a seguinte pergunta: Quais os motivadores dos votos dos Deputados na EMA n.º 22? O objetivo é identificar os principais fatores que explicam essa escolha. A rejeição ocorreu por motivação ideológica ou os congressistas desejavam criar uma barreira à entrada de novos políticos, acabando com uma importante fonte de recursos para as campanhas eleitorais ?

Todas as informações obtidas provêm do portal de Dados Abertos da Câmara dos Deputados e do portal de Dados Abertos do Tribunal Superior Eleitoral (TSE). Na tentativa de encontrar quais os fatores mais correlacionados com o voto dos Deputados foram elencadas algumas variáveis relacionadas às características pessoais, aos aspectos políticos e de financiamento de campanha dos parlamentares. Foram utilizados dois métodos de estimação o *Elastic-Net*, desenvolvito por @zou2005regularization, e um *Logit* padrão. Como resultados tem-se que a hipótese de barreira a entrada não foi constatada. Além disso, a ideologia foi um forte motivador do voto, Deputados mais a direita votaram Sim. Um fator que aumentou a probabilidade de votar Não foi a orientação partidária contrária à proposta. Por fim, destaca-se o comportamento coerente dos Deputados mais financiados por PJ que apresentaram maior chance de votar a favor da medida.

Além desta introdução, este capítulo é composto por mais seis. O próximo traz uma contextualização histórica da EMA n.º 22. Depois é feito o levantamento bibliográfico com os trabalhos que demonstram a importância dos recursos financeiros nas campanhas eleitorais brasileiras, além de traçarem um perfil das doações nos pleitos anteriores. A seção seguinte descreve a metodologia utilizada. A seção 5 descreve a base de dados. Na seção 6 são discutidos os resultados da pesquisa, seguido das considerações finais.





