# Referencial Teórico

O pressuposto que alicerça a discussão é de que as preferências dos votantes, sejam eleitores ou políticos, podem ser representadas espacialmente. Assume-se que cada legislador tem uma posição preferida no espaço abstrato de votação com múltiplas dimensões, essa posição é chamada de ponto ideal [@downs1957economic].

Suponha, por exemplo, que os parlamentares são ordenados em uma reta simbolizando a sua tarifa ótima, variando de 0% a 100%, preferida por cada um para a implementação de um imposto. Um projeto de lei, hipotético, busca modificar tal tarifa para 50%. Caso não seja aprovado, permanece o *status quo*. Neste caso, os parlamentares que preferem uma tarifa próxima à proposta votam por sua aprovação. É possível, inclusive, a depender da disposição dos políticos nessa reta imaginária, traçar uma linha de corte (*cutting line*) capaz de separar quem votou contra ou a favor da medida. Além disso, os individuos com preferências similares ficam próximos um do outro na reta. Neste exemplo, há apenas uma dimensão. Sua representação é feita pela reta. Mas, na prática, cada possível temática: tributação, gastos públicos, segurança e etc., pode ser entendida como uma dimensão. 

Além dessa possibilidade de representação espacial, admite-se que as preferências desses indivíduos são único pico, ou seja, a utilidade cai enquanto a pessoa se move para longe do resultado preferido, e simétricas. Portanto, em cada votação, os parlamentares buscam se aproximar o máximo possível de seu ponto ideal. 

Suponha, para simplificação, que o espaço de votações seja unidimensional. Cada votante deve escolher entre duas opções, *yea* ou *nay*, denotados por $y$ e $n$. Seja $p$ o número de legisladores e a posição ideal do i-ésimo representada por $x_i$, um vetor de tamanho $s$. O número de propostas a serem votadas é denotado por $t$ e os resultados das escolhas são $z_{yl}$ e $z_{nl}$ com $l = 1, ..., t$. Assim, a função utilidade para o i-ésimo legislador na l-ésima votação para a alternativa $j=y,n$ é:

<br>

$$ U_{ijl} = u_{ijl}+ \varepsilon_{ijl} \tag{1B} \label{eq:1B}$$

<br>

Onde $u_{ijl}$ é a parte determinística da função utilidade e $\varepsilon_{ijl}$ é a parte estocástica. Dessa forma, outras temáticas e interesses que não estão ligadas diretamente às propostas a serem escolhidas podem influenciar a escolha do legislador, como por exemplo a troca de apoio em uma outra votação e a opinião pública. Assume-se que tais erros estocásticos são independentes e identicamente distribuídos. Se $U_{iyl} > U_{inl}$ o legislador $i$ vota *yea* na votação $l$, caso contrário vota *nay*.

A parte determinística dessa função é comumente tida como uma Normal. Dessa forma, atribui-se alta utilidade a resultados próximos ao ponto ideal do indivíduo, mas a utilidade se aproxima de zero à medida que as escolhas se tornam cada vez mais distantes. Os legisladores são indiferentes entre duas alternativas extremas, mas são sensíveis a mudanças nas alternativas próximas ao seu ponto ideal. Outra possibilidade de forma funcional é a Quadrática. Assim, conforme as opções se afastam do ponto ideal se tornam cada vez menos preferíveis. Ou seja, os indivíduos são menos sensíveis a mudanças para alternativas distantes de seu ponto ideal. Adotando a forma funcional como Normal, tem-se:

<br>

$$ U_{ijl} = \beta exp\Bigg[\frac{-\omega^2d^2_{ijl}}{2}\Bigg] + \varepsilon_{ijl}\tag{2B} \label{eq:2B}$$

<br>

Onde $d_{ijl}$ é a distância euclidiana do ponto ideal do i-ésimo legislador e o resultado associado a sua j-ésima escolha na l-ésima votação, ou seja, $d_{ijl} = |x_i - z_{jl}|$. $\beta$ e $\omega$ são pesos a serem estimados. Note que, caso fosse assumida uma função utilidade Quadrática, ter-se-ia:

<br>

$$ U_{ijl} = -d_{ijl}^2 + \varepsilon_{ijl} \tag{3B} \label{eq:3B}$$ 

<br>

Quanto ao erro aleatório existem três possíveis distribuições, a Normal, Uniforme e Logística. Além disso, supõe-se que estes são independentes e identicamente distribuídos.

Seja o espaço político formado por $s$ dimensões, a função utilidade, admitida como Gaussiana, dos legisladores será:

<br>

$$ U_{ijkl} = \beta exp\Bigg[\frac{-\sum_{k=1}^{s}\omega_k^2d^2_{ijkl}}{2}\Bigg] + \varepsilon_{ijkl}\tag{4B} \label{eq:4B}$$

<br>

Então, a probabilidade do legislador $i$ votar *yea* na j-ésima votação é:

<br>

$$P_{ijy}=P(U_{ijy}>U_{ijn}) \tag{5B} \label{eq:5B}$$

<br>

Substituindo-se as equações das funções utilidade, tem-se

$$P_{ijy}=P\Bigg(\varepsilon_{ijkn} - \varepsilon_{ijky} < \beta exp\Bigg[\frac{-\sum_{k=1}^{s}\omega_k^2d^2_{ijky}}{2}\Bigg] - \beta exp\Bigg[\frac{-\sum_{k=1}^{s}\omega_k^2d^2_{ijkn}}{2}\Bigg]\Bigg) \tag{6B} \label{eq:6B}$$

<br>

$$P_{ijy}=\Phi\Bigg[\beta\Bigg(exp\Bigg[\frac{-\sum_{k=1}^{s}\omega_k^2d^2_{ijky}}{2}\Bigg] - exp\Bigg[\frac{-\sum_{k=1}^{s}\omega_k^2d^2_{ijkn}}{2}\Bigg]\Bigg)\Bigg]\tag{7B} \label{eq:7B}$$

<br>

A partir daí, podem ser estimados os parâmetros com a função verossimilhança das escolhas observadas dos legisladores: 

<br>

$$L = \prod_{i=1}^{p}\prod_{l=1}^{t}\prod_{j=1}^{2}P^{c_{ijl}}_{ijl} \tag{8B} \label{eq:8B}$$

<br>

Onde $c_{ijl}=1$ se o legislador $i$ votou na alternativa $j$ na votação $l$ e $0$ caso contrário. A partir daí, os parâmetros podem ser estimados, maximizando-se o logaritmo da função verossimilhança.


