# Revisão Bibliográfica

Keith Poole possui mais de trinta anos estudando a estimação de pontos ideais [@poole1985spatial; @poole1985patterns; @poole1997non; @poole2001d; @poole2005spatial]. Recentemente, desenvolveu uma aplicação disponível no site Voteview[^1], que aplica seus algoritmos da família NOMINATE (*Nominal Three Steps Estimation*) para o Senado e Câmara americanos para todas as legislaturas desde 1789.

[^1]: <http://www.voteview.com>

@hix2006dimensions estudaram o Parlamento Europeu (PE) a partir das votações nominais de 1979 até 2001. Utilizando o W-NOMINATE os autores encontraram duas dimensões. A partir da média dos pontos ideais estimados por partido e de medidas exógenas de posição política, interpretaram a primeira dimensão como Esquerda x Direita clássica e a segunda como Governo x Oposição a nível nacional e europeu.

@bailey2007comparable comparou os pontos ideais dos ocupantes da Câmara, Senado, Presidência e Suprema Corte, nos Estados Unidos, de 1951 até 2002. O autor desenvolveu, a partir de uma abordagem Bayesiana, uma metodologia capaz de comparar tais instituições entre si e ao longo do tempo.

@battista2013common conseguiram mapear em uma mesma escala os pontos ideais dos legisladores estaduais norte-americanos nos anos de 1999 e 2000. Os autores utilizaram tanto as votações nominais como uma pesquisa intitulada *National Political Awareness Test*. Para a estimação dos pontos foi utilizada a metodologia de Teoria de Resposta ao Item, com uma modificação no algoritmo que otimiza a função verossimilhança, assim como os algoritmos desenvolvidos por @clinton2004statistical.

@feliu2013tecnicas analisou a distribuição dos pontos ideais dos deputados do Paraguai, por meio das votações nominais da Câmara dos Deputados em 2003. Além do NOMINATE foi utilizado o algoritmo IDEAL, baseado em um método Bayesiano. Como resultado principal, o autor destaca a polarização partidária a partir da dicotomia entre governo e oposição.

Os discursos dos parlamentares também são explorados na construção dos pontos ideais. @proksch2010position investigam como os partidos nacionais e seus respectivos membros se posicionam nos debates do PE, de 1999 a 2004, usando a contagem de palavras dos discursos legislativos e um algoritmo chamado WORDFISH, desenvolvido pelos autores. Por fim, concluíram que os discursos do PE refletem as divisões partidárias sobre a integração da União Européia.

@bonica2014mapping mediu a ideologia de candidatos e doadores, de eleições federais e estaduais nos Estados Unidos, para as campanhas eleitorais usando dados financeiros dessas doações. O estudo englobou o período de 1979 até 2012 e o cálculo dos pontos ideais seguiu a metodologia desenvolvida por @poole1998recovering.

@bond2015quantifying com os dados da rede social *Facebook* estimaram a ideologia de políticos e seus respectivos apoiadores. Os dados utilizados foram coletados em três datas distintas em 2010, 2011 e 2012. A técnica de Análise de Componentes Principais (ACP) foi utilizada, a partir da decomposição em valores singulares (*Singular Value Decomposition - SVD*). Assim como nos demais trabalhos, há uma comparação com os resultados obtidos caso fosse utilizado algum algoritmo da família NOMINATE. Destaca-se que em todos os casos a correlação entre os pontos ideais é elevada.

No caso brasileiro, um dos trabalhos pioneiros foi desenvolvido por @leoni2002ideologia. O seu objetivo principal era quantificar o número de dimensões importantes para representar os Deputados Federais de 1991 até 1998. Para tanto, implementou um dos métodos desenvolvidos por Poole, o W-NOMINATE, com base nas votações nominais feitas por tais parlamentares no período. Como conclusão, destaca-se a quase unidimensionalidade do legislativo brasileiro que é caracterizada pela dicotomia Governo x Oposição.

@power2009estimating partiram de uma pesquisa realizada com os Deputados Federais de 1990 até 2005 onde os próprios se auto classificavam, assim como os partidos que compunham o cenário político do período, em direita e esquerda, em uma escala que variava de zero a dez. Ao todo, foram 850 parlamentares que participaram. Os pesquisadores conseguiram estimar, via Máxima Verossimilhança, a posição ideológica dos deputados, dos principais partidos e do eleitor mediano destes. A conclusão que chegaram foi que as posições obtidas são estáveis ao longo do tempo e que há uma polarização entre PT e PSDB.

Buscando explicar o que faz um parlamentar ter um comportamento diferente de seu líder partidário, @zucco2009ideology calculou os pontos ideais dos Deputados de 1996 até 2006 com base em suas votações nominais e na metodologia W-NOMINATE. Tais pontos foram usados para construir a diferença de comportamento. Como variáveis explicativas, o autor utilizou as emendas parlamentares, quantificadas monetariamente, que beneficiavam certos Deputados frente ao seu eleitorado, algo conhecido na literatura como *Pork barrel*, a ideologia construídas da mesma forma que @power2009estimating é uma variável binária caso o parlamentar fizesse parte do Governo. Com base nisso, montou-se uma estrutura de dados em painel estimados em um modelo agrupado e também uma regressão de Mínimos Quadrados Ordinários (MQO) para cada ano. Como resultado o autor destaca que a ideologia não desempenha nenhum papel na explicação do comportamento do Deputado.

Explorando a mesma pesquisa feita com os ocupantes do legislativo federal, @zucco2011distinguishing estimaram os pontos ideais com base nas votações nominais de 1989 até 2010. Os autores implementaram um método Bayesiano onde a distribuição de probabilidade a priori (*prior*) foi montada a partir da pesquisa destacada. Segundo os mesmo, a vantagem é de que será captada uma dimensão ideológica, algo não garantido pelos métodos da família NOMINATE que apenas selecionam as dimensões que mais explicam os dados. Como conclusão, destacam a importância da dimensão não ideológica de oposição ao governo, onde a mudança dos partidos da coalizão governista implica em mudanças nos pontos ideais na segunda dimensão ao longo do tempo. 

@leite2016analise analisam as votações nominais da Câmara dos Deputados e do Senado, de 2007 até 2014, e da Câmara Municipal de São Paulo de 2013 a 2016. São calculados pontos ideais via ACP comparando-os aos gerados pelo W-NOMINATE. A principal vantagem foi que a ACP permitia utilizar todas as votações feitas e todos os parlamentares, assim como o tempo de execução. Como principal resultado tem-se a multidimensionalidade do legislativo brasileiro.

@martins_rodrigo_mapeando_nodate examinaram as votações na Câmara dos Deputados em 2019 identificando, a partir da OC, praticamente uma única dimensão importante, caracterizada pelo conflito Governo x Oposição. Além disso, propôs uma forma de interpretar a dimensão estimada, concluindo que a maioria das votações importantes estavam ligadas à Reforma da Previdência.

Outros estudos brasileiros investigam outras problemáticas com as mesmas técnicas citadas. @rodrigostf mediu os pontos ideais para os ministros do Supremo Tribunal Federal brasileiro  de 1990 até 2014. O pesquisador comparou métodos da família NOMINATE com a ACP e outra metodologia desenvolvida por @poole1997non a *Optimal Classification* (OC). A conclusão é de que, para o objeto de estudo em questão, a OC apresentou a melhor performance. Embora frise que a interpretação deve prevalecer sobre qualquer métrica.

Já @de2017estimaccao utilizou um método de estimação Bayesiano adaptado de @barbera2015birds. A autora buscou políticos que estavam em exercício em julho de 2017 e que tinham conta ativa na rede social *Twitter*. Os textos publicados e a interação com determinados perfis foram considerados no cálculo dos pontos ideais, porém o intuito era apenas comparar os métodos de estimação existentes com o proposto, nenhuma interpretação sobre os pontos foi feita.





