# Metodologia


## Modelo

Na tentativa de encontrar quais os fatores mais correlacionados com o voto dos Deputados foram elencadas algumas variáveis relacionadas às características pessoais, aos aspectos políticos e de financiamento de campanha dos parlamentares. Estimou-se o seguinte modelo linear.

$$EMA22 = (Pessoais) \boldsymbol \theta  + 
(Políticas) \boldsymbol \gamma +
(Financiamento) \boldsymbol \delta + \boldsymbol u
$$ <br>

Onde $EMA22$ é um vetor $n\times1$ representando o voto de cada dos $n$'s Deputados, $\boldsymbol \theta$, $\boldsymbol \gamma$ e $\boldsymbol \delta$, são vetores dos coeficientes a serem estimados, $\boldsymbol u$ é o vetor $n\times1$ dos distúrbios Não observados e as variáeveis entre parênteses estão descritas no Quadro 3.1.

<br>

| **Variável** | **Descrição** |
| --- | --- |
| EMA22 | Variável com valor igual a 1 caso o Deputado tenha votado Sim e 0 caso tenha votado Não. |
| **Pessoais** |
| Superior | _Dummy_ para Deputado com grau de escolaridade de nível superior - valor 1 para candidatos com nível superior completo e valor 0 caso contrário. |
| Casado | _Dummy_ para o parlamentar casado - valor 1 para casado e 0 para os demais. |
| Político | _Dummy_ para Deputado cuja ocupação declarada ao TSE no pleito de 2014 - valor 1 para era deputado, senador ou vereador e valor 0 caso contrário. |
| Região | _Dummy_ para a região a qual a UF cujo Deputado foi eleito pertence. |
| **Políticas** |
| Ideologia | Variável construída no capítulo anterior pelo método W-NOMINATE. |
| Orientação Contra | _Dummy_ para o parlamentar cujo partido orientou a votar Não na EMA n.º 22. |
| Oposição | _Dummy_ para os parlamentares que Não faziam parte da coligação vencedora nas eleições de 2014 - valor 1 caso pertencesse e 0 caso contrário. |
| **Financiamento** |
| Rec.PJ | Percentual da Receita Total de campanha advinda de doações de pessoas jurídicas. |
| Rec.PF | Percentual da Receita Total de campanha advinda de doações de pessoas físicas. |
| Rec.Próprios | Percentual da Receita Total de campanha advinda de recursos próprios do Deputado. |
| Rec.Partido | Percentual da Receita Total de campanha advinda do partido político do parlamentar. |


<br>

## Método

Devido a existência de uma grande quantidade de variáveis disponíveis e nenhum arcabouço teórico consolidado sobre o tema optou-se por utilizar um método de *Machine Learning* (ML) conhecido como *Elastic Net* e foi desenolvido por @zou2005regularization.

O conjunto de explicativas utilizado para o ML foi composto pela ideologia do parlamentar, a orientação partidária em relação a votação em questão, se o Deputado mudou de partido após a eleição até o momento da votação, se o Deputado era um suplente, o total de votos obtidos na eleição, e se o congressista fazia parte da coligação do Governo. Também foram incluídos o patrimônio declarado à Justiça Eleitoral, os valores absolutos das doações feitas por PF, PJ, outros candidatos e comitês, pelo partido político do próprio Deputado, os recursos próprios utilizados como receita de campanha e também o valor total desta. Além de valores absolutos montou-se o percentual advindo de cada fonte. Como carcaterísticas pessoais mantiveram-se a idade, o sexo, o grau de instrução, o estado civil, a raça e a região a qual a UF, cujo Deputado representava, pertencia.

O ML consiste basicamente em três etapas. Inicialmente, divide-se a amostra em duas partes, aleatoriamente, uma chamada de teste e outra de treino. Utilizou-se a proporção de 75% para teste e 25% para treino, mantendo-se a proporção
na variável resposta. Ou seja, na amostra como um todo cerca de 55% dos Deputados votou a favor da emenda e o restante contra. Essa proporcionalidade foi mantida na base de teste e de treino.

Depois, o modelo proposto é estimado utilizando a amostra de treino. Após a escolha da melhor especificação com base em métricas definidas pelo pesquisador, verifica-se o poder preditivo do modelo na base de teste. Esse processo é feito até que o melhor resultado seja obtido.

Algumas etapas auxiliares foram implementadas. Primeiramente, fez-se um pré-processamento dos dados na base de teste. Todas as variáveis categóricas foram transformadas em binárias. Depois foram imputados valores para os dados ausentes, de acordo com o algoritmo de K Vizinhos mais próximos (KNN). Por fim, foram eliminadas as variáveis com variância próxima de zero.

Na etapa em que o modelo foi treinado, usou-se a validação cruzada conhecida como *CV k-Fold* que consiste em dividir a amostra *k* partes iguais para que sejam escolhidos os hiperparâmetros do modelo. Cada método de estimação tem um conjunto de hiperparâmetros a serem definidos pelo pesquisador. Nesta pesquisa, o *k* escolhido foi igual a 4. Dessa forma, separou-se a primeira parte ($k_1$) e juntaram-se as demais ($k_2$ + $k_3$+ $k_4$ ) onde o modelo foi estimado. Com base nos parâmetros obtidos, testou-se a previsão do modelo em $k_1$. Isso é feito até que todas as subamostras sejam utilizadas como teste. Depois, associado a cada combinação de hiperparâmetros, calcula-se uma medida de qualidade média para as *k* subamostras. 

O algoritmo de ML utilizado nesta pesquisa é uma generalização dos mínimos quadrados ordinários, onde é aplicada uma penalização ao número de coeficientes angulares estimados. Portanto, é feita a seguinte minimização:

$$Min\frac{1}{2N} \sum_{i=1}^{N}(y_i-\beta_0-x_i^T\beta)^2 + 
\lambda[(1-\alpha)|\beta|_1^2 + \alpha|\beta|^2]$$


<br>

Onde $\lambda\geq0$ é o hiperparâmetro de penalização e $0\geq\alpha\geq1$ é o hiperparâmetro de mistura entre os métodos *Ridge* ($\alpha=1$) ou *Lasso* ($\alpha=0$). Como destacado, seus valores são escolhidos pelo pesquisador. Além disso, $x_i$ representa as variáveis explicativas, $y_i$ a variável resposta e $i = 1, ..., N$ e $j = 1, ..., p$ são os preditores. Por fim, $|\beta|_1 = \sum_{j=1}^p|\beta_j|$ e $|\beta|^2 = \sum_{j=1}^p\beta_j^2$.

Voltando ao método de validação cruzada, buscou-se um conjunto de combinações (*grid*) entre $\alpha$ e $\beta$ que alcançasse a melhor média, entre as *k* subamostras, da métrica de avaliação do modelo. Como o intuito desta pesquisa não é previsão, definiu-se como métrica o erro quadrático médio (EQM). Outros modelos de previsão e classificação focam em acurácia, precisão e curva ROC (*Receiver Operating Characteristic*). Uma vez escolhidos os melhores hiperparâmetros, estimou-se o modelo no conjunto de teste, onde foram extraídas as variáveis mais importantes, a partir do valor dos parâmetros estimados e padronizados.

Além do método de ML, empregou-se uma regressão *Logit* usual. Como será visto, o valor de $\lambda$ encontrado foi próximo de zero, permitindo que fosse realizado uma regressão clássica. Nesse caso, mantiveram-se as variáveis explicativas que foram consideradas importantes para explicar o voto do parlamentar. AsSim, características pessoais como Sexo e Raça foram excluídas. Dentre as variáveis de financiamento, optou-se pelo uso dos percentuais em relação à receita total de campanha. O patrimônio foi desconsiderado por ter dados ausentes e ter uma disparidade muito grande entre os Deputados. Quanto às políticas, aquela que indicava se o mesmo era suplente não foi mantida, porque o número de votantes nessa condição era pequeno, total de votos obtidos também foi retirado.

Em suma, mantiveram-se as variáveis apresentadas no Quadro 3.1. A ideologia, como já dito, foi construída no capítulo 2. É importante ressaltar que a variável foi construída para toda a legislatura, portanto é fixa e só muda conforme a migração partidária. Espera-se que parlamentares mais à direita sejam favoráveis à EMA. 

Quanto à orientação partidária contra a emenda, conjectura-se que seja capaz de influenciar a decisão do congressista em votar contrariamente. Para o coeficiente da variável binária que indica se o Deputado era da Oposição não há um sinal esperado *a priori*, uma vez que o Governo não se posicionou sobre o tema, liberando os Deputados para votarem conforme queiram.

Para as variáveis de financiamento, espera-se que aqueles cuja maior fonte de receita seja PJ votem pela aprovação da proposta. Para aqueles cuja maior fonte de financiamento advinda do próprio partido ou de recursos próprios espera-se um sinal negativo. A hipótese é de que ao barrar o financiamento PJ possa ser implementada uma barreira à entrada de novos concorrentes. Pelo mesmo motivo, de diminuir a concorrência, espera-se um parâmetro negativo para *dummy* que indica se o Deputado já era político.

Quanto às regiões, utilizou-se a Centro-Oeste como categoria de referência. AsSim como as demais variáveis de características pessoais, Não são esperados sinais a priori para os coeficientes estimados.














